# Generated by Django 3.2.5 on 2021-10-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('education', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('locality', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('punjab', 'punjab'), ('KPK', 'KPK'), ('Gilgit', 'Gilgit'), ('Sind', 'Sind'), ('Balochistan', 'Balochistan')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(blank=True, upload_to='profile_img')),
                ('my_file', models.FileField(blank=True, upload_to='CV')),
            ],
        ),
    ]
